baseurl         = "https://rakeshtembhurne.github.io/hugo-casper-two-rakesh-bhartiya/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 9
#SectionPagesMenu = "main"
canonifyurls    = true
publishDir = "docs"

[params]
  title       = "Rakesh Tembhurne Bhartiya"
  subtitle    = "I am an Indian, firstly and lastly"
  copyright   = "© 2018"

  cover       = "img/abp_shapath_grahan.png"
  description = "It's a Rakesh Tembhurne Bhartiya's blog. He shares his social and political learnings and opinions thought this blog."
  metaDescription = "Rakesh Tembhurne Bhartiya is a polititian from central India. He is a National IT head of Akhil Bhartiya Pariwar and Vice President MO at JCI Nagpur Metro."
  googleAnalytics = ""
  customCSS = ["css/custom.css"]
  RSSLink = ""

  twitterName = "tembhurnerakesh"
  fbName = "rakeshTembhurneBhartiya"
  # githubName = "eueung"
  # linkedinName = "eueung"
  # mediumName = ""

  # logo = "hugo-logo.png"
  orgName = "Akhil Bhartiya Pariwar"
  orgWebsite = "https://rakesh.bhartiya.me"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Rakesh Tembhurne Bhartiya"
  authorAvatar = "img/rakesh_delhi_profile.jpg"
  authorLocation = "Nagpur, Maharashtra, India"
  authorWebsite = "https://rakesh.bhartiya.me"
  authorDescription = "Rakesh Tembhurne Bhartiya is a polititian from central India. He is a National IT head of Akhil Bhartiya Pariwar and Vice President MO at JCI Nagpur Metro."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Alter Ego"
  url = "https://rakesh.tembhurne.com"
  weight = 95


